#!/usr/bin/python
# Sample check task verifying if the answer is the same with the username
#
import sys

if len(sys.argv) < 3:
    sys.exit(2)

if sys.argv[1] == sys.argv[2]:
    sys.exit(0)

sys.exit(1)